<?php

namespace AppBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
		public function getList()
	{
		$query = $this->createQueryBuilder('p')
			//->where("p.id != 0")
			;

		$query->orderBy('p.position', 'ASC');

		return $query->getQuery()->getResult();
	}

	public function saveClub($page)
	{
		$em = $this->getEntityManager();
		$em->persist($page);
		$em->flush();

		return 0;
	}
}
