<?php

namespace AppBundle\Repository;

/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRepository extends \Doctrine\ORM\EntityRepository
{
	public function getClientsOther($visits)
	{
		$ids = [];
		foreach ($visits as $visit) {
			$ids[] = $visit->getGuest()->getId();
		}

		$query = $this->createQueryBuilder('p');

		if (!empty($ids)) $query->where("p.id NOT IN (".implode(',', $ids).")");

		return $query->getQuery()->getResult();
	}
}