<?php

namespace AppBundle\Repository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStatById($id)
	{
                $parameters = array('id' => $id);
		$query = $this->createQueryBuilder('p')
			->where("p.id_club = :id")
			;
                $query->setParameters($parameters);

		return $query->getQuery()->getResult();
	}
}
