<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAdmins($club_id)
	{
		$query = $this->createQueryBuilder('p')
			->where("p.club = :club_id")
			->andWhere("p.role = 'ROLE_ADMIN'")
			->setParameter("club_id", $club_id)
			;

		return $query->getQuery()->getResult();
	}
}
