<?php

namespace AppBundle\Repository;

/**
 * VisitLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitLogsRepository extends \Doctrine\ORM\EntityRepository
{

}
