# To get started with security, check out the documentation:
# http://symfony.com/doc/current/best_practices/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            form_login:
                check_path: login
                login_path: login
                default_target_path: redirect_after_login

            logout: true
                # path: security_logout
                # target: homepage

    # http://symfony.com/doc/current/book/security.html#securing-url-patterns-access-control
    access_control:
        - { path: ^/efconnect, role: ROLE_SADMIN }
        - { path: ^/elfinder, role: ROLE_SADMIN }
        - { path: ^/sadmin, roles: ROLE_SADMIN }
        - { path: ^/madmin, roles: [ROLE_SADMIN, ROLE_MANAGER] }
